### ISSUE TITLE
a question about this project

### ISSUE THREAD

**Issue by TANHAIYU** [SeongdoKim/VPCalibration#1]
Does this projection needs a initial value of  focal length?

**Comment by SeongdoKim** [comment]
Yes, it requires the initial guess of the focal length. And it is intended to work in a human-made structure.

The algorithm implemented here is the one used in 
[Multi-planar Fitting in an Indoor Manhattan World](https://escholarship.org/content/qt2238w2k7/qt2238w2k7.pdf), explained at the end of Section 4.1.
